stages:
  - build
  
before_script:
  - export LC_ALL=en_US.UTF-8


build_project:
  stage: build
  script:
    - xcodebuild clean -project GryphEats/GryphEats.xcodeproj -scheme GryphEats | xcpretty
    - xcodebuild test -project GryphEats/GryphEats.xcodeproj -scheme GryphEats -destination 'platform=iOS Simulator,name=iPhone XÊ€,OS=13.0' | xcpretty -s
  only:
  - merge_requests
