insert into statictopping values(0, 0, 'Lettuce', 0);
insert into statictopping values(1, 0, 'Tomato', 0);
insert into statictopping values(2, 0, 'Onion', 0);
insert into statictopping values(3, 0, 'Pickles', 0);
insert into statictopping values(4, 0, 'Bacon Strips', 0.5);
insert into statictopping values(5, 0, 'Cheese', 0.5);
insert into statictopping values(6, 0, 'Ketchup', 0);
insert into statictopping values(7, 0, 'Mustard', 0);
insert into statictopping values(8, 0, 'Relish', 0);
insert into statictopping values(9, 0, 'Mayo', 0);
insert into statictopping values(14, 0, 'Mushrooms', 0);
insert into statictopping values(101, 1, 'Tomato', 0);
insert into statictopping values(105, 1, 'Extra Cheese', 0);
insert into statictopping values(110, 1, 'Pepperoni', 0);
insert into statictopping values(111, 1, 'Sausage', 0);
insert into statictopping values(112, 1, 'Bacon Bits', 0);
insert into statictopping values(113, 1, 'Ham', 0);
insert into statictopping values(114, 1, 'Mushrooms', 0);
insert into statictopping values(115, 1, 'Green Peppers', 0);
insert into statictopping values(116, 1, 'Pineapple', 0);
insert into statictopping values(206, 2, 'Ketchup', 0);
insert into statictopping values(217, 2, 'Plum Sauce', 0);
insert into statictopping values(218, 2, 'BBQ Sauce', 0);
insert into statictopping values(219, 2, 'Sweet & Sour Sauce', 0);