insert into statictopping values(0, 0, 'Lettuce', "Salade", 0);
insert into statictopping values(1, 0, 'Tomato', "Tomate", 0);
insert into statictopping values(2, 0, 'Onion', "Oignon", 0);
insert into statictopping values(3, 0, 'Pickles', "Cornichons", 0);
insert into statictopping values(4, 0, 'Bacon Strips', "Lanières de bacon", 0.5);
insert into statictopping values(5, 0, 'Cheese', "Fromage", 0.5);
insert into statictopping values(6, 0, 'Ketchup', "Ketchup", 0);
insert into statictopping values(7, 0, 'Mustard', "Moutarde", 0);
insert into statictopping values(8, 0, 'Relish', "Goût", 0);
insert into statictopping values(9, 0, 'Mayo', "Mayo", 0);
insert into statictopping values(14, 0, 'Mushrooms', "Champignons", 0);
insert into statictopping values(101, 1, 'Tomato', "Tomate", 0);
insert into statictopping values(105, 1, 'Extra Cheese', "Fromage supplémentaire", 0);
insert into statictopping values(110, 1, 'Pepperoni', "Pepperoni", 0);
insert into statictopping values(111, 1, 'Sausage', "Saucisse", 0);
insert into statictopping values(112, 1, 'Bacon Bits', "Lardons", 0);
insert into statictopping values(113, 1, 'Ham', "Jambon", 0);
insert into statictopping values(114, 1, 'Mushrooms', "Champignons", 0);
insert into statictopping values(115, 1, 'Green Peppers', "Poivrons verts", 0);
insert into statictopping values(116, 1, 'Pineapple', "Ananas", 0);
insert into statictopping values(206, 2, 'Ketchup', "Ketchup", 0);
insert into statictopping values(217, 2, 'Plum Sauce', "Sauce aux prunes", 0);
insert into statictopping values(218, 2, 'BBQ Sauce', "Sauce barbecue", 0);
insert into statictopping values(219, 2, 'Sweet & Sour Sauce', "Sauce aigre-douce", 0);